### PR TITLE
Add 'page' to allow reuse of error gen html

### PR DESCRIPTION
**Pull request by ccfontes**
Styles not inlined yet of course.

Maybe you want a different name. I would use it like `noir-exception/page`.

Please tell me if you want some change. I will fixup.

After this I think we are ready for a release.

### CODE REVIEW

**Comment by ccfontes** [comment]
Oops, I forgot to check the look on the README. Give me 2 minutes please.

**Comment by ccfontes** [comment]
It's good to go on my side.

**Comment by yogthos** [comment]
ok should I push it out? :)

**Comment by ccfontes** [comment]
@yogthos Yes. Thanks! :)

**Pull request merged**
